name: chitchat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.15.0
  google_sign_in: 6.1.4
  firebase_auth: ^4.7.1
  lottie: ^2.3.2
  introduction_screen: ^2.1.0
  avatar_glow: 2.0.2
  emoji_picker_flutter: 1.6.1
  get_storage: 2.1.1
  cloud_firestore: 4.8.4
  intl: 0.18.1
  image_picker: 1.0.2
  firebase_storage: 11.2.5
  flutter_launcher_icons: 0.13.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo/icon.png"

flutter: 
  assets: 
    - assets/lottie/
    - assets/logo/
    - assets/models/
  uses-material-design: true

